on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  build_image:
    runs-on: ubuntu-latest
    needs: test  

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t meu-app:latest -f Api/Dockerfile .
